<div class="row">
    <div class="large-12 columns">
        <h1>Crear Servicio</h1>
    </div>
</div>
<hr>
<div class="row">
    <div class="large-12 columns">
        <form action="<?php echo $this->url('create-service'); ?>" method="post">
            <input type="hidden" name="teriId" value="">
            <div class="row">
                <div class="large-3 columns text-right">
                    Orden de Servicio Técnico
                </div>
                <div class="large-2 end columns">
                    <input type="text" name="tervNumber" />
                </div>
            </div>
            <div class="row">
                <div class="large-3 columns text-right">
                    Cliente / Razón Social
                </div>
                <div class="large-9 columns">
                    <input type="text" name="clivName" />
                </div>
            </div>
            <div class="row">
                <div class="large-3 columns text-right">
                    Servicio
                </div>
                <div class="large-9 columns">
                    <input type="text" name="tervService" />
                </div>
            </div>
            <div class="row">
                <div class="large-3 columns text-right">
                    Fecha del servicio
                </div>
                <div class="large-2 end columns">
                    <input type="text" name="terdDate" id="terdDate" value="<?php echo date("d-m-y"); ?>" />
                </div>
            </div>
            <div class="row">
                <div class="large-3 columns text-right">
                    Hora de Inicio
                </div>
                <div class="large-2 end columns">
                    <input type="text" name="terdStartHour" />
                </div>
                <div class="large-3 large-push-2 columns text-right">
                    Hora de Fin
                </div>
                <div class="large-2 columns">
                    <input type="text" name="terdEndHour" />
                </div>
            </div>
            <div class="row">
                <div class="large-3 columns text-right">
                    Supervisor y Asistentes del Servicio
                </div>
                <div class="large-9 columns">
                    <textarea name="tertPersonal" rows="8"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="large-3 columns text-right">
                    Productos Utilizados
                </div>
                <div class="large-9 columns">
                    <textarea name="tertUsedProduct" rows="8"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="large-3 columns text-right">
                    Estado
                </div>
                <div class="large-2 end columns">
                    <select name="teriStatus">
                        <option value="1" selected>Bueno</option>
                        <option value="2">Regular</option>
                        <option value="3">Malo</option>
                    </select>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="large-12 columns">
                    <button class="button radius small">Guardar</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
$(function () {
	$('#terdDate').fdatepicker({
		format: 'dd-mm-yy',
		disableDblClickSelection: true
	});
});
</script>