<div class="row">
    <div class="large-12 columns">
        <h1>Listado de servicios</h1>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <table width="100%">
            <thead>
                <tr>
                    <th width="10%">Orden de Servicio</th>
                    <th width="25%">Cliente</th>
                    <th width="45%">Servicio</th>
                    <th width="9%">Fecha</th>
                    <th width="11%">Acción</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->reports as $report) { ?>
                <tr>
                    <td><?php echo $report->getTervNumber(); ?></td>
                    <td><?php echo $report->getClii()->getClivName(); ?></td>
                    <td><?php echo $report->getTervService(); ?></td>
                    <td><?php echo $report->getTerdDate()->format("d-m-Y"); ?></td>
                    <td>
                        <a href="<?php echo $this->url('view-service', array('id'=>$report->getTeriId())); ?>" class="label secondary">Ver</a>
                        <a href="<?php echo $this->url('delete-service', array('id'=>$report->getTeriId())); ?>" class="label alert">Borrar</a>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="large-12 columns">
        <a href="<?php echo $this->url('create-service'); ?>" class="button tiny">Crear un nuevo servicio</a>
    </div>
</div>